name=DIYables_MiniMp3
version=1.0.0
author=DIYables <diyables.io>
maintainer=DIYables <diyables.io>
sentence=Arduino library for the DIYables Mini Mp3 Player module
paragraph=Easy-to-use Arduino library for the DIYables Mini Mp3 Player module (YX5200-24SS). Communicates via UART. Works with all Arduino boards (Uno, Mega, Nano, Due, Giga), ESP32, ESP8266, and other compatible platforms.
category=Device Control
url=https://diyables.io/products/mini-mp3-player-module
architectures=*
